version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: heart
      POSTGRES_USER: heart
      POSTGRES_PASSWORD: itdaperswerd
    volumes:
      - ~/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '80:3000'
    environment:
      DATABASE_URL: postgres://heart:itdaperswerd@db/heart
      PORT: 3000
    depends_on:
      - db