services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: heart
      POSTGRES_USER: heart
      POSTGRES_PASSWORD: itdaperswerd
    volumes:
      - ~/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5431:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 80:3000
    environment:
      HEART_DATABASE_PASSWORD: itdaperswerd
    depends_on:
      - db